### ISSUE TITLE
Does not compile on rustc 1.14.0-nightly (3f4408347 2016-10-27)

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/aster#118]
```
error[E0063]: missing field `is_shorthand` in initializer of `syntax::ast::Field`
    --> src/expr.rs:1120:21
     |
1120 |         let field = ast::Field {
     |                     ^^^^^^^^^^ missing `is_shorthand`
```

`is_shorthand` added in https://github.com/rust-lang/rust/pull/11994

**Comment by dtolnay** [comment]
Syntex update in https://github.com/serde-rs/syntex/pull/102.
