### ISSUE TITLE
Does not compile for 1.13.0-nightly (5531c314a 2016-09-12)

### ISSUE THREAD

**Issue by zmarcantel** [serde-rs/aster#112]
`0.29.0` currently does not compile with `1.13.0-nightly (5531c314a 2016-09-12)`.

```
error[E0432]: unresolved import `syntax::ext::base::DummyResolver`
 --> /home/my_user/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.29.0/src/mac.rs:3:25
  |
3 | use syntax::ext::base::{DummyResolver, ExtCtxt};
  |                         ^^^^^^^^^^^^^ no `DummyResolver` in `syntax::ext::base`. Did you mean to use `DummyResult`?

error: aborting due to previous error

error: Could not compile `aster`.
```

with

```
rustc 1.13.0-nightly (5531c314a 2016-09-12)
binary: rustc
commit-hash: 5531c314a2855aec368e811da6fcd9e98365af51
commit-date: 2016-09-12
host: x86_64-unknown-linux-gnu
release: 1.13.0-nightly
```

**Comment by dtolnay** [comment]
In general we only support the latest nightly. It compiles now with rustc 1.13.0-nightly (4f9812a59 2016-09-21). If you need to use an old nightly for some reason, you need to enable the `with-syntex` feature like this:

``` toml
[dependencies]
aster = { version = "0.29", features = ["with-syntex"] }
```

This works by backporting the unstable "libsyntax" library from the latest nightly so that you can compile with the old nightly but use libsyntax from the new nightly.

**Comment by zmarcantel** [comment]
Totally my bad.
Was actually a `rustup` bug that was hiding update errors coupled with the fact I can't read (`9-12` versus `9-21`) .
