### ISSUE TITLE
Does not compile with rustc 1.13.0-nightly (1265cbf4e 2016-09-15)

### ISSUE THREAD

**Issue by alexbool** [serde-rs/aster#105]
```
error[E0432]: unresolved import `syntax::ext::base::DummyMacroLoader`
 --> /Users/alexbool/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.26.1/src/mac.rs:3:25
  |
3 | use syntax::ext::base::{DummyMacroLoader, ExtCtxt};
  |                         ^^^^^^^^^^^^^^^^ no `DummyMacroLoader` in `syntax::ext::base`

```

```
$ rustc -vV
rustc 1.13.0-nightly (1265cbf4e 2016-09-15)
binary: rustc
commit-hash: 1265cbf4e05628c98f51afebe0b662c451173faa
commit-date: 2016-09-15
host: x86_64-apple-darwin
release: 1.13.0-nightly
```

Needs serde release as well as I suppose...

**Comment by jchlapinski** [comment]
I have prepared PR for aster https://github.com/serde-rs/aster/pull/106 and syntex https://github.com/serde-rs/syntex/pull/93 that both fix this issue.

Regards,
Jakub

**Comment by jjuraszek** [comment]
if someone (like myself) is rust beginner than this is quick hack which solves this build issue (ie on CI):
add to Cargo.toml

```
[replace]
"aster:0.26.1" = { git = "https://github.com/jchlapinski/aster" }
```

**Comment by oli-obk** [comment]
aster 0.27 has been released

**Comment by alexbool** [comment]
Also need to release serde I suppose?

**Comment by oli-obk** [comment]
good point ^^ I was playing around with serde and totally forgot about releasing
