### ISSUE TITLE
Does not compile on rustc 1.18.0-nightly (50c186419 2017-04-06)

### ISSUE THREAD

**Issue by adeschamps** [serde-rs/aster#133]
```
   Compiling aster v0.41.0 (file:///home/anthony/git/aster)
error[E0560]: struct `syntax::ast::Attribute` has no field named `value`
  --> src/attr.rs:59:13
   |
59 |             value: item,
   |             ^^^^^^ field does not exist - did you mean `path`?

error[E0308]: mismatched types
   --> src/mac.rs:110:18
    |
110 |             tts: self.tokens,
    |                  ^^^^^^^^^^^ expected struct `syntax::tokenstream::ThinTokenStream`, found struct `std::vec::Vec`
    |
    = note: expected type `syntax::tokenstream::ThinTokenStream`
               found type `std::vec::Vec<syntax::tokenstream::TokenTree>`
    = help: here are some functions which might fulfill your needs:
            - .remove(...)
            - .swap_remove(...)

error: no method named `bt_push` found for type `syntax::ext::base::ExtCtxt<'_>` in the current scope
   --> src/mac.rs:141:8
    |
141 |     cx.bt_push(info);
    |        ^^^^^^^

error[E0063]: missing field `span` in initializer of `syntax::ast::PathSegment`
   --> src/path.rs:303:30
    |
303 |         self.callback.invoke(ast::PathSegment {
    |                              ^^^^^^^^^^^^^^^^ missing `span`

error[E0063]: missing field `span` in initializer of `syntax::ast::PathSegment`
   --> src/path.rs:324:30
    |
324 |         self.callback.invoke(ast::PathSegment {
    |                              ^^^^^^^^^^^^^^^^ missing `span`

error: aborting due to 5 previous errors

error: Could not compile `aster`.

To learn more, run the command again with --verbose.
```

**Comment by dtolnay** [comment]
The syntex / aster / quasi stack is not being maintained at the moment - see https://github.com/serde-rs/syntex/issues/114. Please use your own forked version, or switch to a different library.
