### ISSUE TITLE
Does not compile on rustc 1.15.0-nightly (43006fcea 2016-11-15)

### ISSUE THREAD

**Issue by spinda** [serde-rs/aster#123]
```
error[E0308]: mismatched types
    --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/aster-0.33.1/src/expr.rs:2064:92
     |
2064 |         self.builder.build_expr_kind(ast::ExprKind::Closure(self.capture_by, self.fn_decl, block, self.span))
     |                                                                                            ^^^^^ expected struct `syntax::ast::Expr`, found struct `syntax::ast::Block`
     |
     = note: expected type `syntax::ptr::P<syntax::ast::Expr>`
     = note:    found type `syntax::ptr::P<syntax::ast::Block>`
```

**Comment by dtolnay** [comment]
Fixed in 0.34.0.
